version: "1.0.0"

services:
  db:
    image: postgres:alpine
    container_name: portfolio-database
    restart: always
    environment:
      POSTGRES_DB: portfoliodb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    container_name: portfolio-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 8080:80
    volumes:
      - /var/lib/pgadmin
    depends_on:
      - db